Implemented serialized data interface
jlab-sensing/soil-power-sensor-firmware pull request #24
Opened 2024-01-08 17:18 UTC by jmadden173

Most of the code is in `proto/` with `c` and `python` libraries along with tests. Let me know if there is enough documentation available to use both libraries.

2024-01-08 20:25 UTC, stevegtaylor requested changes

2024-01-08 20:25 UTC, stevegtaylor commented on proto/c/include/transcoder.h
File brief could use more detail

2024-01-08 20:25 UTC, stevegtaylor commented on proto/c/include/transcoder.h
encode terosmeasurments brief says encode power measurment

2024-01-08 20:25 UTC, stevegtaylor commented on proto/python/src/soil_power_sensor_protobuf/transforms.py
Please change to doxygen

2024-01-08 20:25 UTC, stevegtaylor commented on stm32/test/test_transcoder/test_transcoder.c
Add description to systemclock_config

2024-01-08 20:25 UTC, stevegtaylor commented on stm32/test/test_transcoder/test_transcoder.c
Where did you get the testing values?

2024-01-08 20:25 UTC, stevegtaylor commented on stm32/test/test_transcoder/test_transcoder.c
More documentation

2024-01-08 20:44 UTC, jmadden173 commented on .github/workflows/publish-python.yaml
TODO: Add comment linking to boilerplate code

2024-01-08 21:44 UTC, jmadden173 commented
@stevegtaylor Updated the documentation and resolved all comments. As a last check can you try running the STM32 tests to check that they work and are configured correctly?

For the CI checks, the publish to TestPyPI failed because it has already been upload. For the ESP32, there is not source files yet therefore fails. Both of these are fine an cannot be fixed in this PR.

2024-01-10 15:39 UTC, jmadden173 commented
@stevegtaylor Update on this?

2024-01-10 16:48 UTC, stevegtaylor commented
> @stevegtaylor Update on this?

Working on openocd right now

2024-01-10 17:55 UTC, stevegtaylor commented
4 tests passed, with the latest code. Had to play around with the location of tool_openocd.py.

2024-01-10 17:57 UTC, stevegtaylor approved these changes

2024-01-14 18:32 UTC, merged